apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: catserver
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    error_log  /var/log/nginx/error.log;
    events {
      worker_connections  128;
    }
    http {
      server {
          listen       80;
          server_name  localhost;
          location /cats {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }
      }
    }