apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cats-pvc
  namespace: catserver
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi